version: "3.8"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN:-example.com}
    volumes:
      - /home/kcn/docker/vaultwarden/data:/data
    ports:
      - 81:80
