version: "3.8"

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea-server
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=${POSTGRES_HOST:-gitea-db}
      - GITEA__database__NAME=${POSTGRES_DB:?POSTGRES_DB not set}
      - GITEA__database__USER=${POSTGRES_USER:?POSTGRES_USER not set}
      - GITEA__database__PASSWD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      - GITEA__server__SSH_PORT=2221
      - GITEA__server__ROOT_URL=http://gitea.kcn.lan
    networks:
      - development
    volumes:
      - /home/kcn/docker/gitea/server:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "30003:3000"
      - "2221:22"
    depends_on:
      - gitea-db
    restart: unless-stopped

  gitea-db:
    image: postgres:14
    container_name: gitea-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER:?POSTGRES_USER not set}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:?POSTGRES_PASSWORD not set}
      - POSTGRES_DB=${POSTGRES_DB:?POSTGRES_DB not set}
    networks:
      - development
    volumes:
      - /home/kcn/docker/gitea/db:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  development:
    external: true
