version: "3.8"

services:
  ntfy:
    image: binwiederhier/ntfy
    container_name: ntfy
    command: serve
    environment:
      - TZ=UTC+1
    volumes:
      - /home/kcn/docker/ntfy/cache:/var/cache/ntfy
      - /home/kcn/docker/ntfy/config:/etc/ntfy
      - /home/kcn/docker/ntfy/data:/var/lib/ntfy
    ports:
      - 82:80
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
