---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

#- greeting:
#    text_size: 4xl
#    text: debian.serwer
#- Kalendarz:
#    widget:
#        type: calendar
- home.serwer:
    - "":
        description: "Debian GNU/Linux 13 (trixie) x86_64"
        ping: 192.168.0.46

    - Home Assistant:
        icon: home-assistant.png
        href: "{{HOMEPAGE_VAR_HOMEASSISTANT_URL}}"
        #description: Smart Home
        ping: "{{HOMEPAGE_VAR_HOMEASSISTANT_URL}}"
        statusStyle: 'dot'
        widget:
          type: homeassistant
          url: "{{HOMEPAGE_VAR_HOMEASSISTANT_URL}}"
          key: "{{HOMEPAGE_VAR_HOMEASSISTANT_KEY}}"
          custom:
            - template: "{{ (states('sensor.energy_monitor_switch_moc') | float(0) + states('sensor.energy_monitor_switch_2_moc') | float(0) + states('sensor.energy_monitor_switch_3_moc') | float(0)) | round(1) }} W"
              label: "Zużycie prądu"
            - state: sensor.temp2_indoor_temperatura
              label: "Temp dom"
            - template: "{{ states('sensor.rack_fan_controller_03_temp_max') | float(0) | round(2) }} °C"
              label: "Temp rack"
            - template: "{{ 'ON' if states('fan.rack_fan_controller_40_fan_top') == 'on' else 'OFF' }}"
              label: "Wentylatory"    



    #- "":
    #- "":
       # widget:
        #    type: coinmarketcap
         #   currency: PLN # Set the currency to Polish Zloty
          #  symbols: [BTC, ETH] # Example cryptocurrencies
           # key: 1a310ffd-5ad9-48ee-85be-528e8342ca23
   # - "":
   #     widget:
   #         type: calendar

- Usługi:
    - Portainer:
        icon: portainer #portainer.svg
        href:  "{{HOMEPAGE_VAR_PORTAINER_URL}}" 
        description: docker
        #server: debian.serwer
        #container: Portainer
        siteMonitor: "{{HOMEPAGE_VAR_PORTAINER_URL}}"
        statusStyle: 'dot'
        widget:
            type: portainer
            url:  "{{HOMEPAGE_VAR_PORTAINER_URL}}" 
            env: 2
            key:  "{{HOMEPAGE_VAR_PORTAINER_API_KEY}}" 
    - piHole:
        icon: pi-hole.svg
        href:  "{{HOMEPAGE_VAR_PIHOLE_URL_2}}" 
        description: dns
        siteMonitor: "{{HOMEPAGE_VAR_PIHOLE_URL}}"
        statusStyle: 'dot'  
        widget:
            type: pihole
            url:  "{{HOMEPAGE_VAR_PIHOLE_URL}}"
            version: 6                              # required if running v6 or higher, defaults to 5
            key:  "{{HOMEPAGE_VAR_PIHOLE_API_KEY_1}}"  
    - Uptime Kuma:
        icon: uptime-kuma.svg
        href:  "{{HOMEPAGE_VAR_UPTIME_KUMA_URL_2}}" 
        description: server monitor
        siteMonitor: "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
        statusStyle: 'dot'
        #widget:
        #   type: uptimekuma
        #   url:  "{{HOMEPAGE_VAR_UPTIME_KUMA_URL}}"
        #   slug: kcn
    - Nginx:
        icon: nginx-proxy-manager.svg
        href: "{{HOMEPAGE_VAR_NGINX_URL_2}}"
        description: proxy manager
        siteMonitor: "{{HOMEPAGE_VAR_NGINX_URL}}"
        statusStyle: 'dot'
    - Duplicati:
        icon: duplicati
        href: "{{HOMEPAGE_VAR_DUPLICATI_URL_2}}"
        description: backup client
        ping: "{{HOMEPAGE_VAR_DUPLICATI_URL}}"
        statusStyle: 'dot'
    - ntfy:
        icon: ntfy.png
        href: "{{HOMEPAGE_VAR_NTFY_URL}}"
        description: server notifications
        ping: "{{HOMEPAGE_VAR_NTFY_URL}}"
        statusStyle: 'dot'
        # widget:
         #  url: "{{HOMEPAGE_VAR_NTFY_URL}}"
         #   topic: "{{HOMEPAGE_VAR_NTFY_TOPIC}}"  
         #   fields: ["message", "lastReceived"]
         #   username: "{{HOMEPAGE_VAR_NTFY_USERNAME}}" 
         #   password: "{{HOMEPAGE_VAR_NTFY_PASSWORD}}"
    - Semaphore:
        icon: semaphore
        href: "{{HOMEPAGE_VAR_SEMAPHORE_URL_2}}"
        description: ansible
        ping: "{{HOMEPAGE_VAR_SEMAPHORE_URL}}"
        statusStyle: 'dot'
    - Gitea:
         icon: gitea
         href: "{{HOMEPAGE_VAR_GITEA_URL_2}}"
         description: git
         ping: "{{HOMEPAGE_VAR_GITEA_URL}}"
         statusStyle: 'dot'

#- Smart Home:

- Media:
     - Immich:
         icon: immich
         href: "{{HOMEPAGE_VAR_IMMICH_URL}}"
         description: photo library
         ping: "{{HOMEPAGE_VAR_IMMICH_URL}}"
         statusStyle: 'dot'
         widget:
            type: immich
            url: "{{HOMEPAGE_VAR_IMMICH_URL}}"
            key: "{{HOMEPAGE_VAR_IMMICH_API_KEY}}"
            version: 2                                  # for Immich >= v1.118
            fields: ["photos", "videos", "storage"]
     - qBittorrent:
         icon: qbittorrent.svg
         href: "{{HOMEPAGE_VAR_QBITT_URL_2}}"
         description: torrent client
         ping: "{{HOMEPAGE_VAR_QBITT_URL_2}}"
         statusStyle: 'dot'
         widget:
             type: qbittorrent
             hideErrors: true
             url: "{{HOMEPAGE_VAR_QBITT_URL_2}}"
             username: "{{HOMEPAGE_VAR_QBITT_USERNAME}}"
             password: "{{HOMEPAGE_VAR_QBITT_PASSWORD}}"
     - Trilium:
         icon: trilium
         href: "{{HOMEPAGE_VAR_TRILIUM_URL_2}}"
         description: notes
         ping: "{{HOMEPAGE_VAR_TRILIUM_URL}}"
         statusStyle: 'dot'
        # widget:
        #    type: trilium
        #    url: "{{HOMEPAGE_VAR_TRILIUM_URL}}"
        #    key: "{{HOMEPAGE_VAR_TRILIUM_KEY}}"

     - Mealie:
         icon: mealie
         href: "{{HOMEPAGE_VAR_MEALIE_URL_2}}"
         description: recipe manager
         ping: "{{HOMEPAGE_VAR_MEALIE_URL}}"
         statusStyle: 'dot'



     #- Jellyfin:
       # icon: jellyfin.svg
       # href: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        #disciption: media center
        #ping: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
        #statusStyle: 'dot'
        #widget: 
         #   hideErrors: true
         #   type: jellyfin
         #   url: "{{HOMEPAGE_VAR_JELLYFIN_URL}}"
         #   key:
         #   enableBlocks: true # optional, defaults to false
         #   enableNowPlaying: true # optional, defaults to true
             
- Sieć:
    - UniFi Network:
        icon: unifi
        href: "{{HOMEPAGE_VAR_ROUTER_URL}}"
        description: Cloud Gateway
        ping: "{{HOMEPAGE_VAR_ROUTER_URL}}"
        #widget:
         #   type: unifi
         #   url: "{{HOMEPAGE_VAR_ROUTER_URL}}"
            #site: default
         #   username: homepage
         #   password: "{{HOMEPAGE_VAR_UNIFY_PASS}}"
         #   verify_ssl: false
         #   refreshInterval: 30
         #   fields:
          #     - "wan_ip"
                #- "wlan"
                #- "lan"
                #- "lan_users"
                #- lan_status
                #- wlan_status
                #- num_clients
                #- num_ap
                #- num_switch
                #- num_gateway
                #- uptime
        #statusStyle: 'dot'
    
    - Kamera:
        icon: /icons/camera2.png
        href: "{{HOMEPAGE_VAR_CAMERA_URL_2}}"
        description: HikVision
        ping: "{{HOMEPAGE_VAR_CAMERA_URL}}"

- "| kCn ~":
    - kcn333.com:
        icon: /icons/www2.svg
        href: https://kcn333.com/
       # description: Homepage
        ping: https://kcn333.com/
        #statusStyle: 'dot' 
    - gitHub:
        icon: /icons/github.svg
        href: https://github.com/kCn3333
        #siteMonitor: https://github.com/kCn3333
        #statusStyle: 'dot'
    - nextCloud:
        icon: nextcloud #owncloud.svg
        href: https://nextcloud.kcn333.com/apps/dashboard/
        ping: https://nextcloud.kcn333.com/
        #statusStyle: 'dot'
    - cloudFlare:
        icon: cloudflare.svg
        href: https://dash.cloudflare.com/login
        #siteMonitor: https://cloudflare.com/
        #statusStyle: 'dot' 
