services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=${JELLYFIN_URL} #optional
    volumes:
      - /home/kcn/jellyfin/config:/config
      - /media/kcn/media:/data/tvshows
      - /media/kcn/media:/data/movies
    ports:
      - 8096:8096 #UI
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      #- 1900:1900/udp #optional DLNA
    restart: unless-stopped