version: "3.8"

services:
  trilium:
    image: triliumnext/notes:latest
    container_name: trilium_notes
    restart: unless-stopped
    ports:
      - "8880:8080"
    volumes:
      - /home/kcn/docker/trilium/data:/home/node/trilium-data
    environment:
      - TRILIUM_DATA_DIR=${TRILIUM_DATA_DIR}
      - TRILIUM_OAUTH_BASE_URL=${TRILIUM_OAUTH_BASE_URL}
      - TRILIUM_OAUTH_ISSUER_BASE_URL=${TRILIUM_OAUTH_ISSUER_BASE_URL}
      - TRILIUM_OAUTH_ISSUER_NAME=${TRILIUM_OAUTH_ISSUER_NAME}
      - TRILIUM_OAUTH_ISSUER_ICON=${TRILIUM_OAUTH_ISSUER_ICON}
      - TRILIUM_OAUTH_CLIENT_ID=${TRILIUM_OAUTH_CLIENT_ID}
      - TRILIUM_OAUTH_CLIENT_SECRET=${TRILIUM_OAUTH_CLIENT_SECRET}
